### ISSUE TITLE
Docker container crashes on fresh install

### ISSUE THREAD

**Issue by PaulKiddle** [SpeciesFileGroup/taxonworks#1495]
I'm trying to run taxonworks locally but not able to. I had it working in February but now when I try the app server crashes:

```
app_1      |  rake aborted!
app_1      | PG::ConnectionBad: could not connect to server: No such file or directory
```

I have removed existing docker containers and volumes and rebuilt images, with no luck.

Any assistance would be appreciated.

**Describe the bug**

`app_1` docker container crashes when running `docker-compose` with a fresh install.

**To Reproduce**
1. When I check out taxonworks git tag `v0.11.0`
2. Then I run `docker-compose build`
3. And I run `docker-compose up`
4. Containers start, app_1 encounters and error and exits

**Logs**
```
db_1       | The files belonging to this database system will be owned by user "postgres".
db_1       | This user must also own the server process.
db_1       | 
db_1       | The database cluster will be initialized with locale "en_US.utf8".
db_1       | The default database encoding has accordingly been set to "UTF8".
db_1       | The default text search configuration will be set to "english".
db_1       | 
db_1       | Data page checksums are disabled.
db_1       | 
db_1       | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1       | creating subdirectories ... ok
db_1       | selecting default max_connections ... 100
db_1       | selecting default shared_buffers ... 128MB
db_1       | selecting dynamic shared memory implementation ... posix
db_1       | creating configuration files ... ok
db_1       | running bootstrap script ... ok
db_1       | performing post-bootstrap initialization ... ok
db_1       | syncing data to disk ... ok
db_1       | 
db_1       | Success. You can now start the database server using:
db_1       | 
db_1       |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1       | 
db_1       | 
db_1       | WARNING: enabling "trust" authentication for local connections
db_1       | You can change this by editing pg_hba.conf or using the option -A, or
db_1       | --auth-local and --auth-host, the next time you run initdb.
db_1       | ****************************************************
db_1       | WARNING: No password has been set for the database.
db_1       |          This will allow anyone with access to the
db_1       |          Postgres port to access your database. In
db_1       |          Docker's default configuration, this is
db_1       |          effectively any other container on the same
db_1       |          system.
db_1       | 
db_1       |          Use "-e POSTGRES_PASSWORD=password" to set
db_1       |          it in "docker run".
db_1       | ****************************************************
db_1       | waiting for server to start....2020-05-15 14:42:04.080 UTC [44] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1       | 2020-05-15 14:42:04.094 UTC [45] LOG:  database system was shut down at 2020-05-15 14:42:03 UTC
db_1       | 2020-05-15 14:42:04.098 UTC [44] LOG:  database system is ready to accept connections
db_1       |  done
db_1       | server started
db_1       | 
db_1       | /usr/local/bin/docker-entrypoint.sh: sourcing /docker-entrypoint-initdb.d/postgis.sh
db_1       | CREATE DATABASE
db_1       | UPDATE 1
db_1       | Loading PostGIS extensions into template_postgis
db_1       | CREATE EXTENSION
db_1       | CREATE EXTENSION
db_1       | CREATE EXTENSION
db_1       | CREATE EXTENSION
db_1       | Loading PostGIS extensions into postgres
db_1       | CREATE EXTENSION
db_1       | CREATE EXTENSION
db_1       | CREATE EXTENSION
app_1      | 
app_1      |  Found config/database.yml 
app_1      | psql: could not connect to server: No such file or directory
app_1      | 	Is the server running locally and accepting
app_1      | 	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
app_1      | 
app_1      | 
app_1      |   !!!!!!!!!! Building a new taxonworks_development database !!!!!!!!!! 
app_1      | 
db_1       | CREATE EXTENSION
db_1       | 
db_1       | 2020-05-15 14:42:06.880 UTC [44] LOG:  received fast shutdown request
db_1       | waiting for server to shut down....2020-05-15 14:42:06.882 UTC [44] LOG:  aborting any active transactions
db_1       | 2020-05-15 14:42:06.883 UTC [44] LOG:  worker process: logical replication launcher (PID 51) exited with exit code 1
db_1       | 2020-05-15 14:42:06.889 UTC [46] LOG:  shutting down
db_1       | 2020-05-15 14:42:07.010 UTC [44] LOG:  database system is shut down
db_1       |  done
db_1       | server stopped
db_1       | 
db_1       | PostgreSQL init process complete; ready for start up.
db_1       | 
db_1       | 2020-05-15 14:42:07.089 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1       | 2020-05-15 14:42:07.089 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1       | 2020-05-15 14:42:07.096 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1       | 2020-05-15 14:42:07.109 UTC [81] LOG:  database system was shut down at 2020-05-15 14:42:06 UTC
db_1       | 2020-05-15 14:42:07.161 UTC [1] LOG:  database system is ready to accept connections
webpack_1  | npm WARN app No repository field.
webpack_1  | npm WARN app No license field.
webpack_1  | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):
webpack_1  | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
webpack_1  | 
app_1      |  rake aborted!
app_1      | PG::ConnectionBad: could not connect to server: No such file or directory
app_1      | 	Is the server running locally and accepting
app_1      | 	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
app_1      | /usr/local/bundle/ruby/2.6.0/gems/pg-1.2.3/lib/pg.rb:58:in `initialize'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/pg-1.2.3/lib/pg.rb:58:in `new'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/pg-1.2.3/lib/pg.rb:58:in `connect'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/activerecord-postgis-adapter-6.0.0/lib/active_record/connection_adapters/postgis/create_connection.rb:38:in `postgis_connection'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:889:in `new_connection'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:933:in `checkout_new_connection'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:912:in `try_to_checkout_new_connection'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:873:in `acquire_connection'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:595:in `checkout'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:439:in `connection'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:1121:in `retrieve_connection'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/connection_handling.rb:238:in `retrieve_connection'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/connection_handling.rb:206:in `connection'
app_1      | /app/config/initializers/constants/model/taxon_name_relationships.rb:10:in `<top (required)>'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:319:in `load'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:319:in `block in load'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:319:in `load'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/engine.rb:667:in `block in load_config_initializer'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.2.2/lib/active_support/notifications.rb:182:in `instrument'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/engine.rb:666:in `load_config_initializer'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/engine.rb:624:in `block (2 levels) in <class:Engine>'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/engine.rb:623:in `each'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/engine.rb:623:in `block in <class:Engine>'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/initializable.rb:32:in `instance_exec'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/initializable.rb:32:in `run'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/initializable.rb:50:in `each'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/initializable.rb:50:in `tsort_each_child'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/initializable.rb:60:in `run_initializers'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/application.rb:363:in `initialize!'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/railtie.rb:190:in `public_send'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/railtie.rb:190:in `method_missing'
app_1      | /app/config/environment.rb:5:in `<top (required)>'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `block in require'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `require'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/application.rb:339:in `require_environment!'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/application.rb:515:in `block in run_tasks_blocks'
app_1      | /usr/local/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
app_1      | /usr/local/bundle/bin/bundle:113:in `load'
app_1      | /usr/local/bundle/bin/bundle:113:in `<main>'
app_1      | Tasks: TOP => db:create => db:load_config => environment
app_1      | (See full trace by running task with --trace)
taxonworks_app_1 exited with code 1
```

**Expected behavior**
All docker containers run, app is accessible at http://localhost:3035/

**Environment (please identify where you experience this bug:**
- Development
- docker v19.03.8, 
- docker-compose v1.24.1,

**Comment by mjy** [comment]
@LocoDelAssembly Problem is where the socket is.  We can add a location in the postgres .cnf file, wherever we are doing that, or we can tweak the application.yml to point to where it is being installed by default.

**Comment by LocoDelAssembly** [comment]
@PaulKiddle @mjy just tried on a clean clone of the repo and checked out v0.11.0. It worked. @PaulKiddle please check if you previously had `config/database.yml`, if you do rename or delete it to give a change the docker environment to set it up for you (or you may just paste the content below)
```yml
default: &default 
  adapter: postgis 
  encoding: utf8
  postgis_extension: true 
  pool: 5 
  timeout: 5000 
  username: postgres 
  host: db
  port: 5432

development: 
  <<: *default 
  database: taxonworks_development 

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run 
# "rake". Do not set this db to the same as development or
# production.
test: 
  <<: *default 
  database: taxonworks_test<%= ENV['TEST_ENV_NUMBER'] %>

```

**Comment by PaulKiddle** [comment]
That's got it working, thank you!
