### ISSUE TITLE
ActiveRecord::StatementInvalid occurred in background (checklist importer)

### ISSUE THREAD

**Issue by LocoDelAssembly** [SpeciesFileGroup/taxonworks#2660]
```
 PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block

  /usr/local/rvm/gems/ruby-3.0.2/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:687:in `exec_prepared'

-------------------------------
Backtrace:
-------------------------------
.
.
.
  /usr/local/rvm/gems/ruby-3.0.2/gems/activerecord-6.1.4.1/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
  /usr/local/rvm/gems/ruby-3.0.2/gems/activerecord-6.1.4.1/lib/active_record/transactions.rb:302:in `save!'
  /usr/local/rvm/gems/ruby-3.0.2/gems/activerecord-6.1.4.1/lib/active_record/suppressor.rb:48:in `save!'
  /app/app/models/dataset_record/darwin_core/taxon.rb:285:in `import'
  /app/app/models/import_dataset/darwin_core.rb:159:in `block (2 levels) in import'
.
.
.
```
https://github.com/SpeciesFileGroup/taxonworks/blob/d54278e10685f0822238eed80c1dfc866b85da1a/app/models/dataset_record/darwin_core/taxon.rb#L285

**Comment by LordFlashmeow** [comment]
I encountered this issue when the wrong name is selected to be the Protonym when the name is a synonym. I had a case where a subspecies was set as the parent of another subspecies. I've made a PR for this in #2715, but there might be other causes as well.

**Comment by LocoDelAssembly** [comment]
Thanks @LordFlashmeow. Just merged, lets see if it improves on this problem as well.

**Comment by mjy** [comment]
Closing as outdated.
