### ISSUE TITLE
[Bug]: LoadError at /taxon_names/1105196 raising javascript modal

### ISSUE THREAD

**Issue by gdower** [SpeciesFileGroup/taxonworks#3595]
### Steps to reproduce the bug

```bash
1. When loading the Root taxon in the browse nomenclature and classification task
2. I frequently get a model javascript error:


ERROR
[object Object]
handleError@http://localhost:3000/packs/js/vendors-node_modules_geoman-io_leaflet-geoman-free_dist_leaflet-geoman_min_js-node_modules_sf-297a4c.js:86355:58
./node_modules/webpack-dev-server/client/overlay.js/createOverlay/<@http://localhost:3000/packs/js/vendors-node_modules_geoman-io_leaflet-geoman-free_dist_leaflet-geoman_min_js-node_modules_sf-297a4c.js:86378:18
```

```
Uncaught (in promise) 
Object { status: 500, statusText: "Internal Server Error", headers: {…}, config: {…}, request: XMLHttpRequest, body: "LoadError at /taxon_names/1105196/otus.json\n===========================================\n\nUnable to autoload constant Queries::Otu::Filter, expected /home/gdo/taxonworks/lib/queries/otu/filter.rb to define it\n\n> To access an interactive console with this error, point your browser to: /__better_errors\n\n\napp/controllers/otus_controller.rb, line 21\n-------------------------------------------\n\n``` ruby\n   16         format.html do\n   17           @recent_objects = Otu.recent_from_project_id(sessions_current_project_id).order(updated_at: :desc).limit(10)\n   18           render '/shared/data/all/index'\n   19         end\n   20         format.json {\n>  21           @otus = ::Queries::Otu::Filter.new(params).all\n   22             .page(params[:page])\n   23             .per(params[:per])\n   24             .eager_load(:taxon_name)\n   25             .order(:cached, 'otus.name')\n   26         }\n```\n\nApp backtrace\n-------------\n\n - app/controllers/otus_controller.rb:21:in `block (2 levels) in index'\n - app/controllers/otus_controller.rb:15:in `index'\n\nFull backtrace\n--------------\n\n - activesupport (6.1.7.6) lib/active_support/dependencies.rb:564:in `load_missing_constant'\n - activesupport (6.1.7.6) lib/active_support/dependencies.rb:213:in `const_missing'\n - app/controllers/otus_controller.rb:21:in `block (2 levels) in index'\n - actionpack (6.1.7.6) lib/action_controller/metal/mime_responds.rb:214:in `respond_to'\n - app/controllers/otus_controller.rb:15:in `index'\n - actionpack (6.1.7.6) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'\n - actionpack (6.1.7.6) lib/abstract_controller/base.rb:228:in `process_action'\n - actionpack (6.1.7.6) lib/action_controller/metal/rendering.rb:30:in `process_action'\n - actionpack (6.1.7.6) lib/abstract_controller/callbacks.rb:42:in `block in process_action'\n - activesupport (6.1.7.6) lib/active_support/callbacks.rb:117:in `block in run_callbacks'\n - actiontext (6.1.7.6) lib/action_text/rendering.rb:20:in `with_renderer'\n - actiontext (6.1.7.6) lib/action_text/engine.rb:59:in `block (4 levels) in <class:Engine>'\n - activesupport (6.1.7.6) lib/active_support/callbacks.rb:126:in `block in run_callbacks'\n - activesupport (6.1.7.6) lib/active_support/callbacks.rb:137:in `run_callbacks'\n - actionpack (6.1.7.6) lib/abstract_controller/callbacks.rb:41:in `process_action'\n - actionpack (6.1.7.6) lib/action_controller/metal/rescue.rb:22:in `process_action'\n - actionpack (6.1.7.6) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'\n - activesupport (6.1.7.6) lib/active_support/notifications.rb:203:in `block in instrument'\n - activesupport (6.1.7.6) lib/active_support/notifications/instrumenter.rb:24:in `instrument'\n - activesupport (6.1.7.6) lib/active_support/notifications.rb:203:in `instrument'\n - actionpack (6.1.7.6) lib/action_controller/metal/instrumentation.rb:33:in `process_action'\n - actionpack (6.1.7.6) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'\n - activerecord (6.1.7.6) lib/active_record/railties/controller_runtime.rb:27:in `process_action'\n - actionpack (6.1.7.6) lib/abstract_controller/base.rb:165:in `process'\n - actionview (6.1.7.6) lib/action_view/rendering.rb:39:in `process'\n - actionpack (6.1.7.6) lib/action_controller/metal.rb:190:in `dispatch'\n - actionpack (6.1.7.6) lib/action_controller/metal.rb:254:in `dispatch'\n - actionpack (6.1.7.6) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'\n - actionpack (6.1.7.6) lib/action_dispatch/routing/route_set.rb:33:in `serve'\n - actionpack (6.1.7.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'\n - actionpack (6.1.7.6) lib/action_dispatch/journey/router.rb:32:in `serve'\n - actionpack (6.1.7.6) lib/action_dispatch/routing/route_set.rb:842:in `call'\n - rack (2.2.8) lib/rack/tempfile_reaper.rb:15:in `call'\n - rack (2.2.8) lib/rack/etag.rb:27:in `call'\n - rack (2.2.8) lib/rack/conditional_get.rb:27:in `call'\n - rack (2.2.8) lib/rack/head.rb:12:in `call'\n - actionpack (6.1.7.6) lib/action_dispatch/http/permissions_policy.rb:22:in `call'\n - actionpack (6.1.7.6) lib/action_dispatch/http/content_security_policy.rb:19:in `call'\n - rack (2.2.8) lib/rack/session/abstract/id.rb:266:in `context'\n - rack (2.2.8) lib/rack/session/abstract/id.rb:260:in `call'\n - actionpack (6.1.7.6) lib/action_dispatch/middleware/cookies.rb:697:in `call'\n - activerecord (6.1.7.6) lib/active_record/migration.rb:601:in `call'\n - actionpack (6.1.7.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'\n - activesupport (6.1.7.6) lib/active_support/callbacks.rb:98:in `run_callbacks'\n - actionpack (6.1.7.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'\n - actionpack (6.1.7.6) lib/action_dispatch/middleware/executor.rb:14:in `call'\n - actionpack (6.1.7.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'\n - better_errors (2.10.1) lib/better_errors/middleware.rb:87:in `protected_app_call'\n - better_errors (2.10.1) lib/better_errors/middleware.rb:82:in `better_errors_call'\n - better_errors (2.10.1) lib/better_errors/middleware.rb:60:in `call'\n - actionpack (6.1.7.6) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'\n - web-console (4.2.1) lib/web_console/middleware.rb:132:in `call_app'\n - web-console (4.2.1) lib/web_console/middleware.rb:28:in `block in call'\n - web-console (4.2.1) lib/web_console/middleware.rb:17:in `call'\n - actionpack (6.1.7.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'\n - railties (6.1.7.6) lib/rails/rack/logger.rb:37:in `call_app'\n - railties (6.1.7.6) lib/rails/rack/logger.rb:26:in `block in call'\n - activesupport (6.1.7.6) lib/active_support/tagged_logging.rb:99:in `block in tagged'\n - activesupport (6.1.7.6) lib/active_support/tagged_logging.rb:37:in `tagged'\n - activesupport (6.1.7.6) lib/active_support/tagged_logging.rb:99:in `tagged'\n - railties (6.1.7.6) lib/rails/rack/logger.rb:26:in `call'\n - actionpack (6.1.7.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'\n - request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'\n - actionpack (6.1.7.6) lib/action_dispatch/middleware/request_id.rb:26:in `call'\n - rack (2.2.8) lib/rack/method_override.rb:24:in `call'\n - rack (2.2.8) lib/rack/runtime.rb:22:in `call'\n - activesupport (6.1.7.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'\n - actionpack (6.1.7.6) lib/action_dispatch/middleware/executor.rb:14:in `call'\n - actionpack (6.1.7.6) lib/action_dispatch/middleware/static.rb:24:in `call'\n - rack (2.2.8) lib/rack/sendfile.rb:110:in `call'\n - actionpack (6.1.7.6) lib/action_dispatch/middleware/host_authorization.rb:148:in `call'\n - rack-cors (2.0.1) lib/rack/cors.rb:102:in `call'\n - shakapacker (7.0.3) lib/shakapacker/dev_server_proxy.rb:25:in `perform_request'\n - rack-proxy (0.7.7) lib/rack/proxy.rb:87:in `call'\n - railties (6.1.7.6) lib/rails/engine.rb:539:in `call'\n - puma (6.4.0) lib/puma/configuration.rb:272:in `call'\n - puma (6.4.0) lib/puma/request.rb:100:in `block in handle_request'\n - puma (6.4.0) lib/puma/thread_pool.rb:378:in `with_force_shutdown'\n - puma (6.4.0) lib/puma/request.rb:99:in `handle_request'\n - puma (6.4.0) lib/puma/server.rb:443:in `process_client'\n - puma (6.4.0) lib/puma/server.rb:241:in `block in run'\n - puma (6.4.0) lib/puma/thread_pool.rb:155:in `block in spawn_thread'\n\n" }
```

### Screenshot

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/8573609/6e145a69-941d-4b03-8bee-37a78d7ea210)

### Expected behavior

Ideally the task should load without throwing an error. It's sporadic with it sometimes throwing an error and sometimes not on the same page hitting reload. It would be great if the modal could be dismissed with the Esc key, or possibly not raised at all because usually the error seems to have no impact on the interface functionality. A smaller modal popup in a screen corner that dismisses itself could also be another way to handle it.

I'm not sure if this is reproducible in sandboxes/production because I mainly use my local development environment.

### Environment

Development (native)

### Sandbox Used

localhost

### Version

 v0.34.6

### Browser Used

Firefox 116.0.3

**Comment by mjy** [comment]
@gdower this is development only, a module scoping issue.  You might want to restart your server, you might also add some rooting to module/class namespaces where there is collision (you'll see an error in the server log).  For example '::Otu' vs. 'Otu.'. In the later case, if we have loaded in dev, say `Queries::Otu::Filter` then we can get collisions.
