### ISSUE TITLE
[Bug]: NoMethodError in Tasks::Dwc::DashboardController#generate_download

### ISSUE THREAD

**Issue by kleintom** [SpeciesFileGroup/taxonworks#3774]
### Steps to reproduce the bug

```bash
Go to the DwC Dashboard task and click on any of the green download buttons, for example All.

I'll put results in a followup comment.
```

### Environment

Sandbox, Development (docker)

### Version

1e584aec1c47308fa240906c44923e9f61e133db

**Comment by kleintom** [comment]
On sandbox I get a popup note reading:  `status: 500 error: Internal Server Error`
In development the popup has more information, which here I've copied from the 500 error in the Network dev tools tab instead:
```
NoMethodError in Tasks::Dwc::DashboardController#generate_download
undefined method `map' for nil:NilClass
Extracted source (around line #73):

  def taxonworks_extension_params
    params.permit(taxonworks_extension_methods: []).dig(:taxonworks_extension_methods).map(&:to_sym)
  end

end

Rails.root: /app
Application Trace | Framework Trace | Full Trace
app/controllers/tasks/dwc/dashboard_controller.rb:73:in `taxonworks_extension_params'
app/controllers/tasks/dwc/dashboard_controller.rb:35:in `generate_download'
Request

Parameters:

{"dwc_occurrence_end_date"=>"2024-01-10",
 "dwc_occurrence_start_date"=>"2024-01-09",
 "per"=>7,
 "dwc_indexed"=>true,
 "format"=>"json",
 "dashboard"=>{"dwc_occurrence_end_date"=>"2024-01-10", "dwc_occurrence_start_date"=>"2024-01-09", "per"=>7, "dwc_indexed"=>true}}
```
