### ISSUE TITLE
[Bug]: Rails 7 not recovering from error state

### ISSUE THREAD

**Issue by kleintom** [SpeciesFileGroup/taxonworks#3956]
### Steps to reproduce the bug

```bash
The title is maybe off, feel free to change. I'll add STR below where they're easier to read.
```

### Environment

Development (docker)

### Version

8f904c50bc2d1f591b18bb112b7bc03b12dca632

**Comment by kleintom** [comment]
STR: I suspect the same will happen on any similar introduced code error, but here's a specific one:

1. Go to /signup. Reload the page as many times as you want, all is fine.
2. Go to the file app/views/users/_form.html.erb for that form and introduce a syntax error, like on line 43 change `f.checkbox` to `f.checkbo`.
3. Reload /signup. Get the expected error page saying `undefined method 'check_bo' for an instance of ActionView::Helpers::FormBuilder`.
4. Now fix the syntax error.
5. Reload /signup.

See the error `can't add a new key into hash during iteration` with backtrace
```
app/models/taxon_name_classification.rb:334:in `map'
app/models/taxon_name_classification.rb:334:in `descendants'
```

6. Reload that page again. Now see the error `uninitialized constant TaxonNameClassification::Icn` with the same backtrace.

7. Now you get the same error trying to load any page.

If I now ctrl-c in my terminal and restart everything then all is good again.

**Comment by mjy** [comment]
I think I understand the base error behind this (`can't add a new key into hash during iteration`).  Will try to refactor the method in question, that does a ton of `map()` etc.

**Comment by mjy** [comment]
@kleintom this may be resolved with the 0882c41 commit, if so please feel free to close.

**Comment by kleintom** [comment]
Seems to be working, thanks!
